export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as Highlights } from "./Highlights"
export { default as Testimonials } from "./Testimonials"
export { default as About } from "./About"
export { default as Footer } from "./Footer"
export { default as BookingForm } from "./BookingForm"
export { default as Modal } from "./Modal"
